# Generated by Django 4.2.23 on 2025-09-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='devedor',
            name='module',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='devedor',
            name='status_code',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='titulo',
            name='operador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
