# Generated by Django 4.2.23 on 2025-09-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_devedor_module_devedor_status_code_titulo_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devedor',
            name='module',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
